#
# Use Manorrock Server
#
FROM manorrock/server:amd64-v20.6.0

#
# Copy Manorrock Savannah into Tomcat 9.
#
COPY target/savannah.war /usr/local/tomcat/webapps/ROOT.war

#
# Copy configuration into Savannah directory.
#
ADD target/savannah.tar.gz /usr/local

#
# Set the JAGORNET_DHCP_HOME
#
ENV JAGORNET_DHCP_HOME /usr/local/savannah
