#
# Use Manorrock Server
#
FROM manorrock/server:arm-v20.6.0

#
# Setup for cross-platform building.
#
RUN ["cross-build-start"]

#
# Copy Manorrock Savannah into Tomcat 9.
#
COPY target/savannah.war /usr/local/tomcat/webapps/ROOT.war

#
# Copy configuration into Savannah directory.
#
ADD target/savannah.tar.gz /usr/local

#
# Set the JAGORNET_DHCP_HOME
#
ENV JAGORNET_DHCP_HOME /usr/local/savannah

#
# End cross platform building.
#
RUN ["cross-build-end"]
